### ISSUE TITLE
nostr and python 3.8

### ISSUE THREAD

**Issue by jp-bennett** [geoffwhittington/meshtastic-bridge#4]
podman start -a owntracks_meshtastic-bridge_1
Traceback (most recent call last):
  File "./main.py", line 12, in <module>
    from plugins import plugins
  File "/code/plugins.py", line 542, in <module>
    from nostr.relay_manager import RelayManager
  File "/usr/local/lib/python3.8/site-packages/nostr/relay_manager.py", line 8, in <module>
    from .relay import Relay, RelayPolicy
  File "/usr/local/lib/python3.8/site-packages/nostr/relay.py", line 10, in <module>
    class RelayPolicy:
  File "/usr/local/lib/python3.8/site-packages/nostr/relay.py", line 15, in RelayPolicy
    def to_json_object(self) -> dict[str, bool]:
TypeError: 'type' object is not subscriptable
exit code: 1

Was able to fix this by bumping the python package to 3.9 in the Dockerfile.

**Comment by VideoFX** [comment]
This worked for me, thanks.

nano /etc/owntracks-meshtastic/meshtastic-bridge/Dockerfile

FROM python:3.9
